### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by satorg** [typelevel/scalacheck#1040]
Hello everyone.
I did some repository cleanup – namely, removed many of stale branches gathered in the repo.
Most of them were those already merged from typelevel-steward.

Also some of the deleted branches were very old ones that didn't receive any updates for 6 years or more with names like `1.11.x`, `1.12.x`, etc. The corresponding release tags are kept intact, of course, but I feel there are close to zero chances that such an old lines will ever get any maintenance. We can always spawn a new branch out of the corresponding release tag, if necessary.

However, there are still some old branches that I am not confident about:

Branch | Updated | Behind | Ahead
-- | -- | -- | --
1.14.0_sonatype | 5 years ago | 1039 | 10
1.14.x | 4 years ago | 825 | 29 | 
1.15.2_sonatype | 3 years ago |  562 | 1

I'm not really sure whether we should keep or drop them.

There's no need for immediate action – I'd just like to keep this issue for a while and collect all the opinions.
However, if someone has any opinion on those branches, leave a comment about it please at your convenience.

Also, even though I tried hard to avoid losing any potentially important branches, but since there were dozens and dozens of them, some such branches might have passed unnoticed. So I would appreciate if everyone who cares could check if there's anything important missing in the repo.

Thank you everyone!

**Comment by rossabaker** [comment]
* 1.14.0_sonatype: the substantial commits are already on main
* 1.14.x: the substantial commits are already on main
* 1.15.2_sonatype: the latest 1.15.x is already on scala-native-0.4

I think they can all be safely cleaned up.

**Comment by satorg** [comment]
The above branches have been dropped.
