### ISSUE TITLE
API doc for Gen.listOfN is misleading

### ISSUE THREAD

**Issue by kneisslm** [typelevel/scalacheck#1059]
It is easy to mistake Gen.listOfN as a function that generate Lists of 0..n elements. This is not the case.

The API documentation for Gen.listOfN states that it "Generates a list with _at most_ the given number of elements. […]"
(emphasis by me).

The property check for it checks that it generates _exactly_ n elements.

```
  property("listOfN") = forAll(choose(0, 100)) { n =>
    forAll(listOfN(n, arbitrary[Int])) { _.length == n }
  }
```
(GenSpecification.scala)

**Comment by satorg** [comment]
Related discussion, just for reference: #844.
