### ISSUE TITLE
Make buildableOf* behave more lazily

### ISSUE THREAD

**Issue by ajknoll** [typelevel/scalacheck#127]
`buildableOfN` currently uses `Traversable.fill` to build collections. Unfortunately, `Traversable.fill` eagerly generates the structure, which gets very expensive when generating deeply nested structures of unbounded size.

Optimally, element evaluation should be deferred until the element is requested so that nested structures are only created if they are actually inspected. It won't help with constrained generators, but it would be a useful optimisation for unconstrained generators.

**Comment by ashawley** [comment]
Thanks for the bug report.  This was likely resolved when Gen.buildableOfN was refactored as part of #575.
