### ISSUE TITLE
Provide Gen and Arbitrary instances of classes from java.time

### ISSUE THREAD

**Issue by jubobs** [typelevel/scalacheck#239]
According to the [official roadmap](http://www.scala-lang.org/news/2.12-roadmap/), Scala 2.12 will require Java 8, which brought us the [`java.time`](https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html) library. A future version of ScalaCheck, when migrating to Scala 2.12, should see the addition of `Gen` and `Arbitrary` instances for classes defined in the `java.time` package.

**Comment by xuwei-k** [comment]
FYI https://github.com/scalaz/scalaz/blob/v7.3.0-M2/tests/src/test/scala/scalaz/std/java/TimeTest.scala#L17-L51

**Comment by xuwei-k** [comment]
https://github.com/47deg/scalacheck-datetime

**Comment by ashawley** [comment]
This was added in #734 and was released in version 1.15.3.

Thanks for the feature request.
