### ISSUE TITLE
Arbitrary instance for Symbol

### ISSUE THREAD

**Issue by phipsgabler** [typelevel/scalacheck#243]
Is there a specific reason that there is no default `Arbitrary` instance for `Symbol`? If not, could you just add something along the lines of 

``` Scala
implicit lazy val arbSymbol: Arbitrary[Symbol] =
  Arbitrary(arbitrary[String].map(Symbol(_)))
```

?

**Comment by non** [comment]
Unfortunately the obvious way to add this implicit breaks binary compatibility (according to MiMA). We could probably work around this by adding a new trait for `object Arbitrary` to extend, but I'll wait until I hear from @rickynils about if (or when) he wants to add this implicit and how.
