### ISSUE TITLE
Add new Gen/Arbitrary instances

### ISSUE THREAD

**Issue by non** [typelevel/scalacheck#280]
Currently adding these breaks binary compatibility. This issue is intended to catalogue all the additional instances we want to add (`Gen`, `Cogen`, and `Arbitrary`).

We should also change the trait containing these instances to an `abstract class`. This way future additions won't create binary incompatibilities.

Here are the instances I can think of:
- [ ] `Function0` instances (#277)
- [ ] `Symbol` instances (#243)
- [ ] `java.math.BigInteger`
- [ ] `java.math.BigDecimal`
- [ ] `java.time.*` instances for Scala 2.12/Java 8 (#239)
- [ ] `Gen.infiniteStream`

(I'll update this list as necessary.)

**Comment by adamgfraser** [comment]
I was thinking of adding a Gen instance for infinite streams. Would there be interest in that?

**Comment by non** [comment]
@adamgfraser Sure, I think a `Gen.infiniteStream[A]` would be really useful.

**Comment by adamgfraser** [comment]
Would people be interested in a `Gen.bigList` instance? I'm thinking that sometimes it can be valuable to generate a random large collection to check the stack safety of a method. You can already do this today with something like `Gen.listofN(10000, arbitrary[A])` but thought it might be a nice convenience to have a generator that produced a mix of normal lists, really big lists, and empty lists similar to what already exists for numbers so users can test multiple cases with one property. This could be implemented as just an additional Gen instance so it wouldn't impact any existing use cases.

At the same time I understand that there is value in not clogging up the API with too many specific use cases as opposed to more general combinators so open to whatever people think is best.

**Comment by non** [comment]
Personally I feel like it's easy enough to use `listOfN` here. I could also imagine someone else publishing a third-party library with a bunch of extra handy `Gen` instances/builders.

**Comment by non** [comment]
@rickynils I just noticed many of the binary-incompatible PRs got merged. Does this mean *master* is ready for these kinds of changes?

**Comment by rickynils** [comment]
@non Yes, master is bumped to 1.14 so we can bring on those changes. However, we should also think about what to do with this feedback: https://twitter.com/extempore2/status/788984845913337856

**Comment by non** [comment]
OK, yeah. I'll give it some thought.

**Comment by kevinmeredith** [comment]
Out of curiosity, why is `java.math.BigDecimal` in your list, @non, but not `scala.math.BigDecimal`?

**Comment by non** [comment]
We already have an `Arbitrary[scala.math.BigDecimal]` https://github.com/rickynils/scalacheck/blob/master/src/main/scala/org/scalacheck/Arbitrary.scala#L202

**Comment by ashawley** [comment]
java.math.BigInteger and java.math.BigDecimal were added by @non in #670

**Comment by ashawley** [comment]
java.time was added in #734 and released in version 1.15.3

**Comment by ashawley** [comment]
Closing as completed.  Kudos to the contributors of these instances.
