### ISSUE TITLE
SBT test runner incorrectly running 'successful' Properties in Play project

### ISSUE THREAD

**Issue by JBlundell** [typelevel/scalacheck#288]
Hi,

I have a problem that I've been struggling with for a while so my last port of call is to raise an issue here. My Play project has a Properties test (with two properties in) by which I use sbt to run the test. If the second/last property fails then then the command will rightly be unsuccessful. However, if only the first property in my test fails then the sbt command is still 'successful'. It must be something to do with the fact it's a Play project because if I remove the PlayScala plugin from the build.sbt, the issue goes away. The first ScalaCheck release where this behaviour occurs is 1.12.3 and still happens at 1.13.3

I'm sure there is something obvious I've missed, my money is on where the tests are located but I've failed to find any reference in the documentation. Hopefully someone can show me where I'm going wrong.

Here is a dummy repo which represents my problem (please ignore the unimaginative names!)
https://github.com/bbc/properties-sbt-issue

And the console output: 

> sbt test
> [info] ! test issue.it should fail: Falsified after 0 passed tests.
> [info] > ARG_0: ""
> [info] + test issue.it should pass: OK, passed 100 tests.
> [info] ! test issue.it should fail: Falsified after 0 passed tests.
> [info] > ARG_0: ""
> [info] + test issue.it should pass: OK, passed 100 tests.
> [info] ScalaCheck
> [info] Passed: Total 0, Failed 0, Errors 0, Passed 0
> [info] Passed: Total 1, Failed 0, Errors 0, Passed 1
> [success] Total time: 5 s, completed 25-Oct-2016 09:42:07

Thanks,

Jack

**Comment by non** [comment]
So just to be clear, if you use 1.12.2 then things are OK? But with 1.12.3 this issue appears?

**Comment by JBlundell** [comment]
Yeah that's correct.

**Comment by non** [comment]
Thanks for reporting this. I'll try to take a look soon and see if I can figure out what is going on.

**Comment by JBlundell** [comment]
No problem. Cheers for getting back to me.

Just to add - when I referred to it working when removing PlayScala plugin, I had to move the test from /test to /src/test/scala as it would be a standard sbt project without the Play plugin. ( (Of course out of desperation I tried to place the test in this location with the plugin enabled but it still didn't work).

**Comment by JBlundell** [comment]
Hi, don't suppose there's any update on this? (We've since updated to 1.13.4 and it stills occurs)

Thanks.

**Comment by xuwei-k** [comment]
https://github.com/rickynils/scalacheck/issues/185 ?

**Comment by SethTisue** [comment]
can anyone confirm whether there is still any issue here? (based on I'm seeing above, we should just close the ticket.)

**Comment by SethTisue** [comment]
closing since nobody has spoken up to the contrary
