### ISSUE TITLE
ScalaCheck should be printing failing seeds by default

### ISSUE THREAD

**Issue by SethTisue** [typelevel/scalacheck#400]
issue title is a quote from https://gist.github.com/non/aeef5824b3f681b9cfc141437b16b014 . (I thought there should be a ticket of record on this.)

background and discussion on https://github.com/rickynils/scalacheck/pull/263

**Comment by Daenyth** [comment]
I'd like this very much - it's easy to have tests pass locally then fail on CI, which can be a pain to resolve if your generated data is large

**Comment by SethTisue** [comment]
PR: https://github.com/typelevel/scalacheck/pull/446

**Comment by ashawley** [comment]
Closing this issue.  A change to show the seed for failed properties by default was merged in #446.
