### ISSUE TITLE
How to generate List of positive, distinct and sorted elements

### ISSUE THREAD

**Issue by ravindrabajpai** [typelevel/scalacheck#442]
```
val uniquePositiveInts: Gen[Set[Int]] = containerOf[Set, Int](posNum[Int])
  check {
    forAll(uniquePositiveInts) { ints =>
      println(ints)
      ints.size <= 30
    }
  }

```
It generates Set with negative ints as well -

```
Set(-3, 28, -26, -23, 34, 27, 71, 12, 54, 76, 7, 3, 48, 50, 67, 16, 11, 72, 26, 55, 23, 8, 75, 58, 82, 4, 79, 68, 62)
Set(-3, 61, 1, 28, -26, -23, 34, 27, 71, 12, 54, 76, 7, 3, 48, 50, 67, 72, 26, 55, 23, 8, 75, 58, 82, 4, 79, 68, 62)

```
I just followed the advice given in #352, seems not working for this case. Also how to keep it sorted.

Also If I make it a list -
`val uniquePositiveInts: Gen[List[Int]] = containerOf[Set, Int](posNum[Int]).map(_.toList)`

It generates duplicate elements, containerOfN works fine though.
```
List(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
List(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
```

**Comment by ashawley** [comment]
You can generate sorted positive lists with the following definition:

```scala
val uniquePositiveInts: Gen[List[Int]] =
  Gen.containerOf[Set, Int](Gen.posNum[Int])
    .map(_.toList)
    .map(_.sorted)
```

I predict you're getting negatives and zeros because of something wrong with your generator, but I can't tell.  If it's not your generator, then it might be ScalaCheck's shrinking.  In that case, than you can either disable shrinking:

```scala
Prop.forAllNoShrink(uniquePositiveInts) { ints =>
```

Or you could define your own shrinking definition:

```scala
implicit val shrinkPositiveInts = Shrink { ns: List[Int] =>
  Stream.iterate(ns.take(ns.size / 2)) { ns: List[Int] =>
    ns.take(ns.size / 2)
  }.takeWhile(_.size > 0) :+ List.empty[Int]
}
```
