### ISSUE TITLE
Kittens is broken in community build

### ISSUE THREAD

**Issue by ashawley** [typelevel/scalacheck#488]
Similar issue to #248 about recursive ADT using `Option`:  
```
[error] PartialOrderSuite:
[error] cats.derived.PartialOrderSuite *** ABORTED ***
[error]   java.lang.StackOverflowError:
[error]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[error]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[error]   at org.scalacheck.ArbitraryLowPriority.arbitrary(Arbitrary.scala:79)
[error]   at org.scalacheck.ArbitraryLowPriority.arbitrary$(Arbitrary.scala:79)
[error]   at org.scalacheck.Arbitrary$.arbitrary(Arbitrary.scala:62)
[error]   at cats.derived.TestDefns$Recursive$.$anonfun$arbitrary$11(adtdefns.scala:78)
[error]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[error]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[error]   at org.scalacheck.ArbitraryLowPriority.$anonfun$arbOption$1(Arbitrary.scala:339)
[error]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[error]   ...
```
One possible fix is #487, that reverts #286.

**Comment by joroKr21** [comment]
Where do you see this? It makes sense, the class is called `Recursive`. We should probably use `Gen.sized`.

**Comment by ashawley** [comment]
Yeah that definition of the recursive class is in a test file called `adtdefns.scala`.

**Comment by ashawley** [comment]
I also had difficulty finding it.  The file should be renamed `testdefns.scala`, or the top-level definition should be `AdtDefns`, not `TestDefns`.

**Comment by ashawley** [comment]
Additionally, you have to run the test from a certain other test `coreJVM/testOnly cats.derived.PartialOrderSuite`.

**Comment by ashawley** [comment]
A fix was merged downstream in https://github.com/typelevel/kittens/pull/180

Now, just need to confirm it's ok in the Community Build after unfreezing.

**Comment by SethTisue** [comment]
I believe this got fixed at some point.
