### ISSUE TITLE
Arbitrary/Gen[Instant]?

### ISSUE THREAD

**Issue by kevinmeredith** [typelevel/scalacheck#492]
I propose adding an `Arbitrary[Instant]` or `Gen[Instant]`. In https://github.com/http4s/http4s/pull/2724/commits/9a3aad2f93540bdda2d02e3e764e689db5443d1c, I created one using https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#MIN and https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#MAX.

What are folks' thoughts, please, about adding it to this library?

Also - thanks for this library!

**Comment by ashawley** [comment]
I believe there are some java.time generators in [scalacheck-toolbox](https://github.com/47deg/scalacheck-toolbox).  I'm not sure this kind of thing will be landing in ScalaCheck, see discussion in #456.

**Comment by kevinmeredith** [comment]
Thanks @ashawley. I'll close per your link to #456.

**Comment by kevinmeredith** [comment]
I opened https://github.com/47deg/scalacheck-toolbox/pull/64.
