### ISSUE TITLE
drop Scala 2.10 support

### ISSUE THREAD

**Issue by xuwei-k** [typelevel/scalacheck#505]

**Comment by non** [comment]
It would be interesting to know how many (if any) of our downstream dependencies still support 2.10.

(I'm not saying that would justify keeping it, I'm just curious.)

**Comment by SethTisue** [comment]
my experience in the community build is that most projects have dropped 2.10 from their cross-builds already, and for the ones that haven't, it's almost always just inertia: it isn't causing trouble so why remove it until it does.

I cannot (offhand, anyway) think of a single project where the maintainers are digging in that they actually really want, or consider it important, to keep 2.10 in their cross-build. such projects might exist, but I think it must be pretty rare.

the Scala OSS community is already starting to drop 2.11 from crossbuilds. (not that I'm suggesting ScalaCheck do that, it just adds perspective to the 2.10 question.)

**Comment by ashawley** [comment]
This makse sense to me.  I'd be fine with even dropping Scala 2.11 after the 1.14 series if it could be done.

I suppose ScalaTest is the one important hold out.  Last I checked, the 3.1.0 SNAPS were still publishing for 2.10.

**Comment by SethTisue** [comment]
> I suppose ScalaTest is the one important hold out. Last I checked, the 3.1.0 SNAPS were still publishing for 2.10.

(but note that in the 3.1 series, ScalaTest no longer depends on ScalaCheck. instead, there is a separate scalatestplus-scalacheck repo and artifact)

**Comment by ashawley** [comment]
Should we wait until 1.15.0 to drop Scala 2.10?  It would be nice to have ScalaTest 3.0.x be able to update to ScalaCheck 1.14.1, IMO.

**Comment by SethTisue** [comment]
I was skeptical about waiting, but I think the ScalaTest thing convinces me

**Comment by ashawley** [comment]
Resolved by #572.
