### ISSUE TITLE
Travis-CI config should cache things

### ISSUE THREAD

**Issue by SethTisue** [typelevel/scalacheck#507]
even our new trimmed-down CI matrix has a quite a few jobs in it, and CI takes a while to run

one thing that could help would be if entries were added to `.travis.yml` to cache directories for scala, sbt, .ivy2, etc so that they don't have to be re-retrieved each time

volunteer?

**Comment by b-hass** [comment]
I would be happy to open a PR for this!

**Comment by ashawley** [comment]
That would be great.

https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html#Caching

**Comment by SethTisue** [comment]
fixed by #513
