### ISSUE TITLE
Travis-CI build badge in README isn't working

### ISSUE THREAD

**Issue by SethTisue** [typelevel/scalacheck#511]
build is green, but the badge shows:
<img width="143" alt="Screen Shot 2019-08-14 at 1 18 07 PM" src="https://user-images.githubusercontent.com/161079/63053175-0339c400-be96-11e9-801c-f25bfc6e97dc.png">

**Comment by ashawley** [comment]
Looks right to me.  Last merge to master failed to build in Travis:

https://travis-ci.org/typelevel/scalacheck/builds/570042125

Something about JDK not installing correctly.

**Comment by SethTisue** [comment]
but I clicked on the badge and it took me to a green build — which I see now was actually a green build for a pull request :-/

**Comment by SethTisue** [comment]
the URL in the badge seems appropriate, so I guess the fact that it takes you to an unhelpful place is a problem at Travis's end, not a problem in this repo :-/

and as for the failing builds, looks like more of the recent flakiness; I went around just now and hit "restart" on all the red matrix entries (which was about 15% of them, something like that)

**Comment by ashawley** [comment]
I always thought the main page for a project on Travis was the last build on a main branch, and not a PR.  I wonder if it changed, or I just never noticed this.

**Comment by SethTisue** [comment]
and as for the "the build was failing, but nobody noticed" aspect of this, https://github.com/typelevel/scalacheck/pull/512 should help
