### ISSUE TITLE
next steps: 1.15.0 versus 1.14.2

### ISSUE THREAD

**Issue by non** [typelevel/scalacheck#540]
First, some background:

 - The 1.14.x series will maintain source- and binary-compatibility with 1.14.0.
 - The 1.15.x series will preserve binary-compatibility with 1.14.0 but is expected to **break** source-compatibility (e.g. removing the `implicit` keyword from some definitions)
 - We are planning to drop support for Scala 2.10 in 1.15, but we kept this in for the 1.14.1 release.

Now that 1.14.1 is out, @ashawley and I were discussing next steps. My proposal is that we start merging PRs intended for 1.15.x to `master`. If we don't encounter major bugs in 1.14.1 I'd prefer not to have to do a 1.14.2 release and go right to 1.15.0. If we _do_ need 1.14.2, we can create a `1.14.x` branch off of the `1.14.1` tag at that time and go from there.

How does that sound? Any objections? Am I missing anything?

cc @SethTisue @ashawley et al.

**Comment by smarter** [comment]
i suggest creating a 1.14.x branch just for the record even if nothing more ends up pushed to it.

**Comment by ashawley** [comment]
Yes, a 1.14.x branch would likely be useful.  It's what's been done in the past.

**Comment by ashawley** [comment]
FYI: In light of #557, we will have to consider a 1.14.2 release.

**Comment by non** [comment]
1.14.2 is released -- once we've attached the release notes I'll post about it publicly.

**Comment by ashawley** [comment]
Thanks, Erik, for doing the release.  

I expect in the age of Scala Steward we probably get a lot of downstream projects running a release quicker than in years previous.
