### ISSUE TITLE
Publish 1.14.1 for Scala.js 0.6 and Scala 2.10

### ISSUE THREAD

**Issue by ashawley** [typelevel/scalacheck#555]
While trying to bump ScalaCheck in ScalaTest, their CI caught that Scala.js for 0.6 and Scala 2.10 is missing, see https://github.com/scalatest/scalatest/pull/1706

**Comment by non** [comment]
I went ahead and manually published 1.14.1 for 2.10 with JS 0.6.

We should definitely also merge #556 but it's possible this will unblock the ScalaTest PR.

**Comment by ashawley** [comment]
Thanks, Erik.  It looks good.

https://repo1.maven.org/maven2/org/scalacheck/scalacheck_sjs0.6_2.10/1.14.1/
