### ISSUE TITLE
Gen.posNum is really slow

### ISSUE THREAD

**Issue by sjoerdmulder** [typelevel/scalacheck#567]
Took a while to figure out in our test suite but it seems that using `Gen.posNum` is really slow;
```
forAll(Gen.posNum[Long]) { nr =>
      nr should be > 0l
}
``` 
This takes more than 400 millis (minSuccessful = 100) on my machine

But running 
```
forAll(Gen.choose(1, Long.MaxValue)) { nr =>
      nr should be > 0l
}
``` 
Completes in just 10ms on the same machine

**Comment by non** [comment]
@sjoerdmulder Reading the code in _master_, one of the big difference between `choose` and `posNum` is using the `sized` combinator. Could you also benchmark this using the following generator?

```scala
Gen.sized(n => Gen.choose(1L, java.lang.Long.max(n, 1L)))
```

I notice you're doing this testing from ScalaTest. What versions of ScalaCheck/ScalaTest are you doing? Did you test ScalaCheck directly?

When I did some benchmarking in the REPL using ScalaCheck directly (in the _master_ branch) I didn't see the slowdown you mentioned:

```scala
import org.scalacheck.{Gen, Prop}

scala> def timeit[A](body: => A): A = {
  val t0 = System.nanoTime()
  val res = body
  println("took %d ms".format((System.nanoTime() - t0) / 1000000L))
  res
}
timeit: [A](body: => A)A

scala> timeit(Prop.forAll(Gen.choose(0L, Long.MaxValue))(_ > 0L).check)
+ OK, passed 100 tests.
took 82 ms

scala> timeit(Prop.forAll(Gen.choose(0L, Long.MaxValue))(_ > 0L).check)
+ OK, passed 100 tests.
took 5 ms

scala> timeit(Prop.forAll(Gen.choose(0L, Long.MaxValue))(_ > 0L).check)
+ OK, passed 100 tests.
took 4 ms

scala> timeit(Prop.forAll(Gen.posNum[Long])(_ > 0L).check)
+ OK, passed 100 tests.
took 8 ms

scala> timeit(Prop.forAll(Gen.posNum[Long])(_ > 0L).check)
+ OK, passed 100 tests.
took 4 ms

scala> timeit(Prop.forAll(Gen.posNum[Long])(_ > 0L).check)
+ OK, passed 100 tests.
took 3 ms
```

**Comment by non** [comment]
Based on #568 my guess here is that ScalaCheck is using a very small size here, which makes it likely that we need to retry very frequently. (I'm still be interested in seeing your results for these other benchmarks though.)

**Comment by sjoerdmulder** [comment]
Hi, i'm not sure what i tested yesterday; but indeed it seems that it was caused by JVM warming or Scalatest startup. Running it multiple times with `timeit` doesn't show significant differences.

Sorry for the trouble!

The real problem i had was #568 which suddenly caused our tests to fail because of `None` results.

**Comment by ashawley** [comment]
I realize the OP may be using ScalaTest, but want to note that if you are writing properties directly in ScalaCheck, you can use the `-verbosity 2` option in sbt to get timings.  

I added the `Gen.choose` versions of existing `Gen.posNum` and `Gen.negNum` tests of ScalaCheck's test suite in a private branch [ashawley@posnum-v-choose](https://github.com/ashawley/scalacheck/commit/posnum-v-choose)

```
sbt:scalacheck> jvm/testOnly org.scalacheck.GenSpecification -- -verbosity 2
[info] + Gen.posNum[Int]: OK, passed 100 tests.
[info] Elapsed time: 0.426 sec 
[info] + Gen.negNum[Int]: OK, passed 100 tests.
[info] Elapsed time: 0.027 sec 
[info] + Gen.posNum[Long]: OK, passed 100 tests.
[info] Elapsed time: 0.010 sec 
[info] + Gen.negNum[Long]: OK, passed 100 tests.
[info] Elapsed time: 0.009 sec 
[info] + Gen.posNum[Float]: OK, passed 100 tests.
[info] Elapsed time: 0.019 sec 
[info] + Gen.negNum[Float]: OK, passed 100 tests.
[info] Elapsed time: 0.009 sec 
[info] + Gen.posNum[Double] <= 1.0d: OK, passed 100 tests.
[info] Elapsed time: 0.015 sec 
[info] + Gen.choose(1, Int.MaxValue): OK, passed 100 tests.
[info] Elapsed time: 0.007 sec 
[info] + Gen.choose(Int.MinValue, -1): OK, passed 100 tests.
[info] Elapsed time: 0.005 sec 
[info] + Gen.choose(1L, Long.MaxValue): OK, passed 100 tests.
[info] Elapsed time: 0.006 sec 
[info] + Gen.choose(Long.MinValue, -1L): OK, passed 100 tests.
[info] Elapsed time: 0.005 sec 
[info] + Gen.choose(1.0, Float.MaxValue): OK, passed 100 tests.
[info] Elapsed time: 0.004 sec 
[info] + Gen.choose(Float.MinValue, -1.0): OK, passed 100 tests.
[info] Elapsed time: 0.003 sec 
[info] Passed: Total 13, Failed 0, Errors 0, Passed 13
```

It also confirms the JVM warming issue.
