### ISSUE TITLE
documentation page has bad links

### ISSUE THREAD

**Issue by oscar-stripe** [typelevel/scalacheck#574]
https://www.scalacheck.org/documentation.html

see for instance "online":

https://www.scalacheck.org/files/scalacheck_2.11-1.14.1-api/index.html

**Comment by erik-stripe** [comment]
Thanks for reporting this.

@rickynils do you know how those files get populated? Do I need to do something during the release? Should I try to host the Scaladocs somewhere else and you can just link to them?

**Comment by non** [comment]
Thanks for reporting this.

@rickynils do you know how those files get populated? Do I need to do something during the release? Should I try to host the Scaladocs somewhere else and you can just link to them?

**Comment by non** [comment]
This ties into a more general problem: we still need @rickynils to update the static site.

It's possible we should move the site to something hosted in Github, so @ashawley and I can manage it. What do you all think?

**Comment by deanwampler-domino** [comment]
I just noticed this same bug, 1.5 years later.

**Comment by ddl-deanwampler** [comment]
And again... Let me know if I can help move it to a GitHub site.

**Comment by rossabaker** [comment]
I could flip the switch to enable publishing to ghpages, but we'd need the domain owner's help to have scalacheck.org point at it.

**Comment by rickynils** [comment]
@rossabaker I can do that, just tell me where I should point the domain

**Comment by rossabaker** [comment]
Thanks, @rickynils.  It turns out it's not as easy as flipping the switch: I didn't find source here to point to.  I fixed that in #850.  If you've been managing this with a static site generator and can link to the source, we could use that instead.

Once that's merged, I can enable GitHub pages, and then we should just need [the apex domain and www subdomain variant](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain) set up in your DNS.

**Comment by rickynils** [comment]
@rossabaker The existing site is generated by using a combination of [Hakyll](https://jaspervdj.be/hakyll/) and [Nix](https://nixos.org/manual/nix/stable/). I can make the source available, but I wonder if it wouldn't be better for the current maintainers to start over with something they feel comfortable to maintain?

**Comment by rossabaker** [comment]
I'm comfortable with Nix, but I'm barely a maintainer here.  I'm happy with #850 as an interim solution to give the regular maintainers time to discuss what they're comfortable with.

**Comment by ashawley** [comment]
I'd be fine with Hakyll, too.  I'm sure the sources for the Hakyll and Nix site could be useful for getting the site updated, and coming up with what the long-term solution is.

**Comment by SethTisue** [comment]
> I'm comfortable with Nix

I’m enjoying the casual understatement here

**Comment by rossabaker** [comment]
If @rickynils can share the sources, I should be able to locally render a gh-pages branch from it fairly trivially to get this unblocked.  That would replace #850.

I could also hack together a Hakyll and Nix job for CI if that's the long-term solution, but that's only good if a maintainer more regular than me wants to keep that stack.

**Comment by rickynils** [comment]
I will extract the sources from the larger private repo they are part of now and make sure they still build. I'll get back to you when I have something working.

**Comment by rickynils** [comment]
@rossabaker I've extracted the sources, fixed the build and pushed to a new repo at https://github.com/typelevel/scalacheck-web. See build instructions in the README. Ping me if you have any troubles understanding my nix code.

Feel free doing what you like with that repo, maybe you'd like to integrate the web sources in the main repo instead.

**Comment by ashawley** [comment]
Thanks for doing this, Rickard.

I agree that it would be ideal to integrate the website sources in to the main branch, but if we're interested in adding CI it would need to be a separate branch or repo to avoid inefficiently building the sources.  If that's the case, we likely have to keep it in a separate repo or branch?

I know that like other static-site generators, [Hakyll can be made to support ghpages](https://jaspervdj.be/hakyll/tutorials/github-pages-tutorial.html).  We'd need to see if CI, like GitHub Actions, would be able to publish to the gh-pages branch and how.

**Comment by rossabaker** [comment]
Thanks, Rickard.  I need to upgrade to Nix 2.4 before I can run that, but that's been on my todo list anyway.

Unless we're doing something with mdoc for compiled examples, I'd think site generation could just be a separate CI workflow that doesn't even touch the Scala.

**Comment by rossabaker** [comment]
Oh, I see what @ashawley means now on inefficiency.  I pushed the code into a subdir, and it's of course dutifully building all the code.  We can fix that with `paths` in the workflow, I think.

**Comment by ashawley** [comment]
> Unless we're doing something with mdoc for compiled examples, I'd think site generation could just be a separate CI workflow that doesn't even touch the Scala.

I agree.  I don't envision we'd need to have the website be part of the source code.  I saw you opened a PR upstream at sbt-github-actions plugin to get paths working, but I'm not so sure the plugin would play well with automating the publishing to gh-pages, anyway.  Maybe we should just keep it separate for the sake of simplicity for now.  Would you be willing to change your current PR so the website sources are just a separate branch from the library sources?  Then, we can just use the `website` branch going forward (and no need to merge your PR).  I can update CONTRIBUTING and the README that that's where the site sources are located.

**Comment by rossabaker** [comment]
Yep, that sounds reasonable to me.  I'll do that, and archive the other repo.

**Comment by rossabaker** [comment]
Sorry I didn't get back to this sooner.  My PR is now just the root of the `website` directory.  There are no changes to the generated version currently in `gh-pages`.

**Comment by SethTisue** [comment]
Volunteer to PR a fix to the actual issue this ticket is about, now that Ross and Rickard (🙏🙏🙏) have addressed the infra issues that were blocking a fix?

**Comment by ashawley** [comment]
Thanks, Ross!  Looks great.

**Comment by ashawley** [comment]
I believe this particular issue is fixed.  We just need Rickard to point scalacheck.org to the gh-pages.

**Comment by rickynils** [comment]
@ashawley @rossabaker I've pointed scalacheck.org to the gh-pages now. It seems to be working. Traffic is going through CloudFlare and they are also adding SSL (just as before). Please tell me if you want me to disable the CloudFlare layer.

**Comment by ashawley** [comment]
Looks good, thanks Rickard!

I don't see anything wrong with having Cloudfare in the mix to help handle the domain hosting.  I recall gh-pages is tricky to get working for both the apex domain and the www.scalacheck.org.  These all still work, so any existing links in the universe should be happy.

http://scalacheck.org
https://scalacheck.org
http://www.scalacheck.org
https://www.scalacheck.org

**Comment by ddl-deanwampler** [comment]
Yay! Looks great. Thanks for fixing this.

**Comment by SethTisue** [comment]
all is well
