### ISSUE TITLE
Integral types generate less often

### ISSUE THREAD

**Issue by lorenzhawkes** [typelevel/scalacheck#577]
It looks like the fix for #439 has caused positive and negative Integral sub types of Numeric to be generated less often. This looks to be because zero is chosen more often and then filtered out which the old implementation did not do.

**Comment by ashawley** [comment]
This behavior was fixed in a follow-up in #569.  It has not been released, though.

**Comment by lorenzhawkes** [comment]
Great, thanks.

**Comment by ashawley** [comment]
There are snapshots published when commits are pushed to master.

If you're using sbt, you can use them with the the following snippet:

```scala
resolvers +=
  "Sonatype OSS Snapshots" at
  "https://oss.sonatype.org/content/repositories/snapshots"
```

Then this is the version that contains the merge of #569:

```scala
libraryDependencies += "org.scalacheck" %% "scalacheck" % "1.14.2-e3883f6-SNAPSHOT" % "test"
```

Feel free to give it a try.
