### ISSUE TITLE
Publish 1.14.2 artifact for ScalaJS 1.0.0-RC1

### ISSUE THREAD

**Issue by ashawley** [typelevel/scalacheck#587]
This came up in #585 which was a PR to master, but there is no 1.15 release planned.  Artifacts for 1.14.2 should be published in the meantime.

**Comment by ashawley** [comment]
I've pushed up 7e08d2f to the 1.14.x branch.

I'm looking at the `release.sh` script, and am realizing that it doesn't really support just publishing Scala.js artifacts, unfortunately.

**Comment by SethTisue** [comment]
note that Scala.js has 1.0.0-RC2 has been published
