### ISSUE TITLE
Add a function similar to Gen.resultOf to Cogen

### ISSUE THREAD

**Issue by nigredo-tori** [typelevel/scalacheck#589]
Currently to build a `Cogen` for some type (`A`) that is isomorphic to another type (`B`) for which a `Cogen` exists, we need to summon the `Cogen[B]`, and `contramap` it. This leads to noisy code like this:

```scala
implicit val InstantCogen: Cogen[Instant] =
  Cogen[(Long, Int)].contramap(i => (i.getEpochSecond, i.getNano))
```

It should be easy to add `Cogen.resultOf` that would derive a `Cogen[A]` given a function `A => B` (and the implicit `Cogen[B]` in scope), similarly to what `Gen.resultOf` does. We would then be able to write:

```scala
implicit val InstantCogen: Cogen[Instant] =
  Cogen.resultOf(i => (i.getEpochSecond, i.getNano))
```

**Comment by non** [comment]
We merged #590 to master. Thanks! Closing.
