### ISSUE TITLE
Publish 1.14.3

### ISSUE THREAD

**Issue by ashawley** [typelevel/scalacheck#591]
I was going to try and prepare a release of Scala.js 1.0.0-RC1 in #587 but it might be better to just release 1.14.3 with the Scala.js artifacts and with the bug-fix in #569.  

Plus, a 1.0.0-RC2 version of Scala.js was released, yesterday.

**Comment by ashawley** [comment]
Drafted the release notes in #593.

**Comment by ashawley** [comment]
Going to cherry-pick the Scala.js 0.6.31 update while we're at it, see #594.

**Comment by SethTisue** [comment]
perhaps the release note should mention that https://github.com/typelevel/scalacheck/issues/581 got fixed as well (as a consequence of the #568 fix)

**Comment by ashawley** [comment]
That's a good question.  I read #581 as the same issue in #568.  We can just close as a duplicate.

However, the issue with collection generators having a higher probability of failing because of the poor performing `posNum` or any unreliable generator will live on in #568.  Erik suggested it could be improved somehow.

**Comment by ashawley** [comment]
Dear @djspiewak,

I've tagged commit 6464e984a07168e329ca55b38d863ad4e89f6952 as 1.14.3, on the 1.14.x branch, and pushed up the tag.  Would you be able to deploy the branch?  Just start reading the directions at the top of the shell script, `release.sh`.  You can start at step 4.  This is a relatively new script that is a WIP, so apologies in advance if it gives you trouble.

Thank you!

**Comment by djspiewak** [comment]
Script appears to be working! Release is uploading.

**Comment by djspiewak** [comment]
@ashawley Looks like the script is missing a `sonatypeReleaseAll` command. I'll run that manually.

**Comment by djspiewak** [comment]
Oh holy crap it's not using sbt-sonatype. Wow. Okay I closed the staging repository by hand. We should probably fix that. :-)

**Comment by djspiewak** [comment]
Kk if I did things correctly, 1.14.3 should be propagating to Maven Central.

**Comment by ashawley** [comment]
Thanks, Daniel.  Will keep an eye out for them.

**Comment by ashawley** [comment]
Are you seeing them, yet?  I'm not seeing anything.  Looking here for instance:

https://repo1.maven.org/maven2/org/scalacheck/scalacheck_2.13/1.14.3/

**Comment by djspiewak** [comment]
Just goes to show how long it's been since I released anything on Sonatype by hand… I forgot to *release* the repository; I just closed it. It should be syncing now. I think.

**Comment by djspiewak** [comment]
Also, appropriately enough, @xerial reacted to my post above. Much love!

**Comment by xerial** [comment]
Yeah. I'm waiting for the release :)

I guess it's a timing to automate the release on CI with sbt-sonatype. Here is some example https://github.com/wvlet/airframe/blob/master/.github/workflows/release.yml

or using sbt-ci-release will be handy https://github.com/olafurpg/sbt-ci-release

**Comment by ashawley** [comment]
Ok, looks like they got released.  Thanks again for the help.

**Comment by djspiewak** [comment]
> I guess it's a timing to automate the release on CI with sbt-sonatype. Here is some example https://github.com/wvlet/airframe/blob/master/.github/workflows/release.yml

Yeah it wouldn't be too difficult to do this, honestly, though I personally prefer with OSS projects to keep the actual release process local to a developer machine (since it's not clear who's GPG key and Sonatype credentials get ceded to Travis' control, but it's not an entirely comfortable feeling either way). At the very least, using sbt-sonatype rather than manually publishing to Sonatype would be a good and easy step forward.

**Comment by ashawley** [comment]
Yeah, sorry about all the difficulty.  I guess I'll look in to doing it myself in the future.  I've just been putting it off.

**Comment by djspiewak** [comment]
It actually wasn't all that bad. Just ran into some issues that should be reasonably easy to fix.

**Comment by xerial** [comment]
@djspiewak It makes sense. Having a script to publish from a local machine will be a good starting point. 

1. Build artifacts for all cross-build combinations (e.g., Scala.js 0.6.x, 1.0.x) into a local staging folder
2. Run sonatypeBundleRelease once.
