### ISSUE TITLE
Update repo with 1.14.3 version

### ISSUE THREAD

**Issue by ashawley** [typelevel/scalacheck#598]
We released version 1.14.3 of ScalaCheck.  It would be good to mention it in the README and update to it in the examples.  There may be other places, as well.

https://github.com/typelevel/scalacheck/search?q=%221.14.2%22&unscoped_q=%221.14.2%22

This only needs to be done to `master`, not to `1.14.x` branch.

**Comment by non** [comment]
We should also try to get it mentioned on the website (along with 1.14.2): http://www.scalacheck.org/

cc @rickynils
