### ISSUE TITLE
Class cast exception on hashmap

### ISSUE THREAD

**Issue by vaslabs** [typelevel/scalacheck#602]
Hello,
There seems to be an issue when having a large enough Map generated and probably being accessed concurrently. 

The error I get is this

`Exception: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode`

https://circleci.com/gh/vaslabs/sbt-kubeyml/123?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I think the conditions to generate the issue is to have a large enough hashmap, with enough hash conflicts to cause the creation of a tree node and also building the map concurrently.

**Comment by SethTisue** [comment]
Are you sure this is a bug in ScalaCheck? I don't see any usages of `java.util.HashMap` inside ScalaCheck itself.

**Comment by vaslabs** [comment]
I can do some research after the holidays, my theory is that scalacheck does some construction in parallel of a Map which is mutable so under the hood the builder is a java hash map.

Can you assign this issue to me and not close it so I can have it in my list and not forget about it, and I'll let you know what I find in a couple of weeks

**Comment by ashawley** [comment]
If you can reproduce locally, I believe you should be able to use `-verbosity 2` to get a backtrace.

**Comment by vaslabs** [comment]
thanks

**Comment by vaslabs** [comment]
Hello everyone and happy new year!

I try to replicate the issue locally but I couldn't .

I got the docker image that I found the issue in circle ci 
```
docker pull circleci/openjdk@sha256:02e718add366a0cefa0a0f6e197382edd7bfae48b7c14d17d94ad73c1949d597
```
But the issue did not happen again even though I left it running for a few ours

The java version on both the container and my machine are the same anyway
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```

This looks like it's very rare. I couldn't find a single line of code in the scalacheck codebase that generates a data structure with parallelisation (e.g. a parallel stream).

Same goes for the rest of the libraries in the path of the error (circe and mine).

Either I missed something for replicating this or this is somewhere else.
For reference the scala version is **2.12.10**

A few notes:
 
1. Scalacheck builds a map with a map builder that uses a (scala) HashMap under the hood if size gets bigger than 4. The end (immutable) Map is internally a polymorphic array of HashMap (HashMap1 - single element hashmap or a HashTrieMap) . This was successful when the error happened anyway which makes it probably improbable for scalacheck to have done something to break a java hashmap.

On that note I think this issue can be closed.

**Comment by vaslabs** [comment]
To anyone interested I isolated the issue to another library
Thanks @ashawley for the verbosity hint
Looks like it's coming from snakeyml
build: https://circleci.com/gh/vaslabs/sbt-kubeyml/151

`Exception: java.lang.ClassCastException: java.util.HashMap$Node cannot be
   cast to java.util.HashMap$TreeNode
java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1835)
java.util.HashMap$TreeNode.putTreeVal(HashMap.java:2014)
java.util.HashMap.putVal(HashMap.java:638)
java.util.HashMap.put(HashMap.java:612)
org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseC
  onstructor.java:219)
org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstruc
  tor.java:205)
org.yaml.snakeyaml.constructor.SafeConstructor.processDuplicateKeys(SafeCon
  structor.java:85)
org.yaml.snakeyaml.constructor.SafeConstructor.flattenMapping(SafeConstruct
  or.java:70)
io.circe.yaml.parser.package$FlatteningConstructor.flatten(package.scala:44
  )
io.circe.yaml.parser.package$.yamlToJson(package.scala:92)
io.circe.yaml.parser.package$.$anonfun$parse$1(package.scala:21)
scala.util.Either.flatMap(Either.scala:341)
io.circe.yaml.parser.package$.parse(package.scala:20)
io.circe.yaml.parser.package$.parse(package.scala:24)
kubeyml.ingress.KubernetesComponents$.pathVariable(KubernetesComponents.sca
  la:96)
kubeyml.ingress.KubernetesComponents$.$anonfun$rule$1(KubernetesComponents.
  scala:109)
scala.collection.immutable.List.map(List.scala:286)
kubeyml.ingress.KubernetesComponents$.rule(KubernetesComponents.scala:109)
kubeyml.ingress.KubernetesComponents$.$anonfun$ingress$1(KubernetesComponen
  ts.scala:130)
scala.collection.immutable.List.map(List.scala:290)
kubeyml.ingress.KubernetesComponents$.ingress(KubernetesComponents.scala:13
  0)
kubeyml.ingress.KubernetesComponents$.ingress(KubernetesComponents.scala:14
  2)
kubeyml.ingress.IngressJsonSpec.$anonfun$new$2(IngressJsonSpec.scala:39)
kubeyml.ingress.IngressJsonSpec.$anonfun$new$2$adapted(IngressJsonSpec.scal
  a:38)`

**Comment by vaslabs** [comment]
For anyone looking in the future this is fixed in circe-yaml 
https://github.com/circe/circe-yaml/pull/114
