### ISSUE TITLE
Publish 1.14.3 for Scala.js 1.0

### ISSUE THREAD

**Issue by ashawley** [typelevel/scalacheck#623]
Dear @djspiewak,

Would you be willing to do another release of 1.14.3 for Scala.js 1.0?  You could probably tinker with the `release.sh` script, but maybe the easiest thing would be to just manually run sbt yourself:

    $ env IS_RELEASE=true SCALAJS_VERSION="1.0.0" sbt +js/clean +js/publishSigned

The commit is 0f3a63f183c79a31c44bc45959b175ca77761e6d on the 1.14.x branch.

Much appreciated,
Aaron

**Comment by ashawley** [comment]
Ping @djspiewak

**Comment by djspiewak** [comment]
Okay I think it's done. It always messes me up that this project doesn't use sbt-sonatype yet.

**Comment by ashawley** [comment]
I'm not seeing anything, yet.  Last time, https://github.com/typelevel/scalacheck/issues/591#issuecomment-565558311, you had to hit release to publish them.

**Comment by djspiewak** [comment]
I'll take a check tonight. I did close the repo. Not sure why it wouldn't be there.

**Comment by djspiewak** [comment]
…we really need to get sbt-sonatype in there.

**Comment by SethTisue** [comment]
it would be sweet to get on sbt-ci-release

**Comment by djspiewak** [comment]
I honestly dislike doing CI releases for OSS, just because the key management problem is considerably more impactful (and more challenging). But really… anything would improve things. :-)
