### ISSUE TITLE
Deprecation warnings because of Stream

### ISSUE THREAD

**Issue by froth** [typelevel/scalacheck#626]
I am currently porting code to scala 2.13 and am not able to get rid of deprecation warnings concerning Stream (replaced by LazyList) because of it's use in the interface of Shrink.

Is there a way to do so? A second apply method in Shrink would be handy:
  def apply[T](s: T => LazyList[T]): Shrink[T] = ???

Or am I missing something?

**Comment by ashawley** [comment]
This is more of a Scala question than a ScalaCheck question.  However, we also ran in to it.  We just disable fatal warnings in the 2.13 portion of the build:

https://github.com/typelevel/scalacheck/blob/d5967d2/build.sbt#L88

**Comment by ashawley** [comment]
Concerning ScalaCheck still using Stream for shrinking:  We have to support multiple versions of Scala, including Scala 2.11 and Scala 2.12, so we haven't moved to LazyList for shrinking, yet.  It's on the list of things to do for ScalaCheck 2.0.

**Comment by froth** [comment]
Would it be possible to support both types in your interface until then? (see above)
That would mean that ScalaCheck still has the deprecation warnings (which is sad) but would allow for users to write code that does not throw these warnings.

**Comment by ashawley** [comment]
I believe there are a couple of issues with switching to LazyList for shrinking.  It would be nice if it didn't require 2.0, but I recall it did.  It was a while ago, and I didn't investigate it thoroughly, though.  It was about the time we were working on 2.13 in #411.

**Comment by SethTisue** [comment]
> But maybe one could do a scala 2.13 compatability package. But I am not sure if that would be worth it.

It wouldn't need to be a separate package, it could just be some Scala-version-specific sources. I think a pull request that did this would be accepted (at least, I don't see why not).

**Comment by froth** [comment]
I'll have a look and see what I can do

**Comment by froth** [comment]
Created a draft pull request. I am not sure about the name of the helper, so happy for suggestions on that point.

Or on anything else as I do not know scalacheck that well.

**Comment by ashawley** [comment]
Thanks for looking in to it.  Maybe there will be a way.  We'll just need to consider any impact on the eventual switch to LazyList for Shrink down the road and significant changes planned for Shrink.
