### ISSUE TITLE
Publish for Scala.js 1.0.0 

### ISSUE THREAD

**Issue by exoego** [typelevel/scalacheck#629]
It would be great if scalacheck published for Scala.js 1.0.0, so Scala.js users can update Scala.js to 1.0.0.

It seems that dependencies had been already updated in https://github.com/typelevel/scalacheck/pull/622

**Comment by SethTisue** [comment]
this already happened:

* https://repo1.maven.org/maven2/org/scalacheck/scalacheck_sjs1_2.11/1.14.3/
* https://repo1.maven.org/maven2/org/scalacheck/scalacheck_sjs1_2.12/1.14.3/
* https://repo1.maven.org/maven2/org/scalacheck/scalacheck_sjs1_2.13/1.14.3/

**Comment by exoego** [comment]
Oh, I missed them.
Thanks !!
