### ISSUE TITLE
Add Choose[BigInt]

### ISSUE THREAD

**Issue by dmurvihill** [typelevel/scalacheck#631]
ScalaCheck's arbitrary BigInt is bounded, which can be very limiting for some applications and requires e.g. scientific and cryptographic users to implement custom generators. Providing a `Choose[BigInt]` implementation could save considerable boilerplate. This is my implementation:

```scala
  implicit object chooseBigInt extends Gen.Choose[BigInt] {
    @tailrec
    def choose(min: BigInt, max: BigInt): Gen[BigInt] = {
      val n = min + BigInt((max - min).bitLength, Random)
      if (n > max) choose(min, max) else n
    }
  }
```

Any interest in a PR?

**Comment by ashawley** [comment]
Yeah, the bounds of arbitrary BigInt is by design.  An implementation of `Gen.choose[BigInt](min,max)` is missing, however.  Yes, a contribution would be welcome for BigInt, and for BigDecimal if you're interested.

**Comment by ashawley** [comment]
A ticket for BigDecimal is #637.  I thought there might be some commonality, but it seems like BigInt may be a dependency of BigDecimal.

**Comment by ashawley** [comment]
@dmurvihill  has an open PR in #636.  We began to realize that there are practical limits of what ScalaCheck can offer in coverage of BigInt values in terms of performance.  As @non pointed out, there are other practical issues, including printing large failing BigInt values.  Given these limits, I wonder what safe guards ScalaCheck should provide to `Gen.choose[BigInt]`?
