### ISSUE TITLE
Backport Dotty build to 1.14.x branch

### ISSUE THREAD

**Issue by larsrh** [typelevel/scalacheck#663]
Dotty builds currently only happen on `master`. I'd like to volunteer adding the build to 1.14.x. The next 1.14.x release could include a cross-built artifact for Dotty. Is this desired?

**Comment by ashawley** [comment]
Is there a need?  Does the `withDottyCompat` trick not work in your sbt build?

**Comment by larsrh** [comment]
I guess it would, but I thought it'd be nice to have a cross release for such a foundational library.

**Comment by larsrh** [comment]
Turns out I overestimated the need. There's currently a discussion happening at typelevel/discipline#161, so I'm closing this for now and will re-open if the consensus changes.
