### ISSUE TITLE
Release 1.15.0

### ISSUE THREAD

**Issue by ashawley** [typelevel/scalacheck#668]
In #667, @smarter said:

> @non @ashawley once this is in, what do you think about releasing 1.15.0? According to #540 it was supposed to come shortly after 1.14.1. It'd be great to get it out for the improved dotty usability from finally getting rid of the ambiguous implicit error due to BooleanOperators.

**Comment by ashawley** [comment]
I agree we should release 1.15.0.

I've worked on applying the 1.15.0 label to open issues, so we can track progress and the remaining effort:

https://github.com/typelevel/scalacheck/milestone/10

**Comment by smarter** [comment]
How critical are the remaining issues in the 1.15.0 milestone? Could some of them be moved to a future milestone to release 1.15.0 faster ?

**Comment by larsrh** [comment]
Would be much appreciated. Happy to volunteer the time to upgrade the Typelevel ecosystem.

**Comment by SethTisue** [comment]
@ashawley are you around and interested in helping push this forward? (fsvo "helping")

**Comment by ashawley** [comment]
I should have free time soon to contribute to getting a release out here.  Sorry for the delay.

**Comment by SethTisue** [comment]
note that one possibility would be to just close our eyes, roll whatever we have and call it 1.15.0-M1 (or 1.15.0-RC1), and then work towards 1.15.0 final after

thought prompted because I just hit "ambiguous implicit error due to BooleanOperators" myself today over at https://github.com/scala/scala-parallel-collections/pull/113, so now I know what y'all are talking about there :-)

**Comment by non** [comment]
@SethTisue i'll do that this weekend

**Comment by non** [comment]
@SethTisue So, the Dotty build is blocking the release. Specifically, it appears it didn't build javadoc jars, which Sonatype checks for when validating the release. Here the publish output from Dotty:

```
[info]  published scalacheck_0.24 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalac
heck_0.24/1.15.0-M1/scalacheck_0.24-1.15.0-M1.pom.asc
[info]  published scalacheck_0.24 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalac
heck_0.24/1.15.0-M1/scalacheck_0.24-1.15.0-M1-sources.jar.asc
[info]  published scalacheck_0.24 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalac
heck_0.24/1.15.0-M1/scalacheck_0.24-1.15.0-M1.jar
[info]  published scalacheck_0.24 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalac
heck_0.24/1.15.0-M1/scalacheck_0.24-1.15.0-M1.pom
[info]  published scalacheck_0.24 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalac
heck_0.24/1.15.0-M1/scalacheck_0.24-1.15.0-M1.jar.asc
[info]  published scalacheck_0.24 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalac
heck_0.24/1.15.0-M1/scalacheck_0.24-1.15.0-M1-sources.jar 
```

And here's Scala 2.12 (JVM):

```
[info]  published scalacheck_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalac
heck_2.12/1.15.0-M1/scalacheck_2.12-1.15.0-M1-javadoc.jar.asc                                                          
[info]  published scalacheck_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalacheck_2.12/1.15.0-M1/scalacheck_2.12-1.15.0-M1.pom.asc                                                                  
[info]  published scalacheck_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalacheck_2.12/1.15.0-M1/scalacheck_2.12-1.15.0-M1-sources.jar.asc                                                          
[info]  published scalacheck_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalacheck_2.12/1.15.0-M1/scalacheck_2.12-1.15.0-M1.jar                                                                      
[info]  published scalacheck_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalacheck_2.12/1.15.0-M1/scalacheck_2.12-1.15.0-M1.pom                                                                      
[info]  published scalacheck_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalacheck_2.12/1.15.0-M1/scalacheck_2.12-1.15.0-M1-javadoc.jar                                                              
[info]  published scalacheck_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalacheck_2.12/1.15.0-M1/scalacheck_2.12-1.15.0-M1.jar.asc                                                                  
[info]  published scalacheck_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalacheck/scalacheck_2.12/1.15.0-M1/scalacheck_2.12-1.15.0-M1-sources.jar
```

As you can see Dotty only published 5 jars while 2.12 published 8.

I don't know a lot about how Dotty publishes. Is this expected? Is there some other SBT command I need to run for Dotty?

**Comment by smarter** [comment]
This comes from your sbt build: https://github.com/typelevel/scalacheck/blob/b2963973ec83c30116cddca2fc83125383bfef2e/build.sbt#L170-L174
The usual workaround to keep sonatype happy is to still publish a doc jar but leave it empty, this is accomplished by having in your sbt build:
```scala
sources in (Compile, doc) := Seq()
```
except here you only want to do it for dotty so you probably want:
```scala
sources in (Compile, doc) := {
  if (isDotty.value) then Seq() else (sources in (Compile, doc)).value
}
```

**Comment by non** [comment]
@smarter Thanks!

**Comment by smarter** [comment]
You could also turn off the dotty build for now: the scalacheck is att version 0.24.0-RC1 so it's way too old to be useful currently anyway. You could try bumping it to `0.27.0-RC1` but that might require porting some commits from the version of scalacheck in our community build: https://github.com/dotty-staging/scalacheck/commits/a715860a25ad6d2c6e1ae17e8baa13ded427cdf0

**Comment by non** [comment]
@smarter I'll try with what I have since it's currently on and already running. If this build fails, I'll turn it off for now and we can revisit.

**Comment by non** [comment]
OK yeah the SBT snippet didn't totally work so I released without Dotty. We can try to fix this before the real 1.15.0 release.

**Comment by non** [comment]
Anyway, just released 1.15.0-M1.

**Comment by larsrh** [comment]
I released a 0.27 artifact based on #684, which isn't yet merged, but since we're talking about a milestone release, I don't think that's problematic.

**Comment by SethTisue** [comment]
thanks Erik, thanks Lars! the 0.27 artifact is working great for me over in scala-parallel-collections :+1:

**Comment by non** [comment]
Do you all feel like we should go ahead and release 1.15.0? I'm also up for doing an M2 if folks would rather be cautious.

**Comment by SethTisue** [comment]
(no opinion)

**Comment by larsrh** [comment]
There's a few open PRs tagged with 1.15.0. I suggest to go through with them and then follow up with RC1.

**Comment by non** [comment]
@larsrh Sounds good. I'm fine with merging both as-is or making changes. Would appreciate at least one more set of eyes.

**Comment by larsrh** [comment]
Are we ready for RC1? @SethTisue, @non?

**Comment by larsrh** [comment]
RC1 is out, final will follow next week if no issues are found.

**Comment by SethTisue** [comment]
okay if we keep this open until actual 1.15.0 is out?

**Comment by larsrh** [comment]
I took the liberty of filling in the gaps in the changelog.

**Comment by larsrh** [comment]
## Release plan

Since Scalacheck doesn't use macros, many library authors that depend on Scalacheck used `withDottyCompat`. Now that we have a proper release, we need to get those out of the way, otherwise sbt complains about conflicting artifact qualifiers (`_0.27` vs. `_2.13`).

* [ ] scalameta/munit#231
* [ ] scalatest/scalatestplus-scalacheck#41
* [ ] specs2 (pending)

**Comment by SethTisue** [comment]
Added to release notes:

> This release was brought to you by 16 contributors, according to git shortlog -sn --no-merges 1.14.3..1.15.0. Thank you Scala Steward, Aaron S. Hawley, Erik Osheim, Lars Hupel, Dolan Murvihill, Alexey Kotlyarov, Zak, Seth Tisue, Taro L. Saito, Neville Li, P. Oscar Boykin, Guillaume Martres, Sean C. Sullivan, Fred Roth, Jonas Kölker, NthPortal.

**Comment by SethTisue** [comment]
@larsrh may I suggest that Typelevel tweet about this? possible tweet text:

> ScalaCheck 1.15.0 is out! 👏🙏 to @aaron_s_hawley @d6 @larsr_h @rickynils and everyone else who contributed https://github.com/typelevel/scalacheck/releases/tag/1.15.0

**Comment by SethTisue** [comment]
if you omit yourself out of modesty I will be VERY ANGRY

**Comment by larsrh** [comment]
I did not, but I did include you :wink:
