### ISSUE TITLE
Drop native 0.3 from build

### ISSUE THREAD

**Issue by ashawley** [typelevel/scalacheck#703]
The first native 0.3 version was released 3 years ago, and the current is 0.4.0-M2.  ScalaCheck has 1.14 and 1.15 artifacts published for both.

It would seem the 0.3 and 0.4 artifacts should be supported during the 1.15.x series, but the former could be dropped for 1.16.x series.

All of this probably hinges on if-and-when native 0.4 final ships.

**Comment by larsrh** [comment]
We should probably also drop Scala.js 0.6.x, I reckon.

**Comment by SethTisue** [comment]
Scala.js 0.6 was dropped in https://github.com/typelevel/scalacheck/pull/713
Scala Native 0.3 was dropped in #751
