### ISSUE TITLE
Simplify GitHub Actions workflow

### ISSUE THREAD

**Issue by larsrh** [typelevel/scalacheck#706]
From https://github.com/typelevel/scalacheck/pull/705#issuecomment-722624942:

> It's ready to merge IMO. The only tweaks it needs are to poke some holes in the matrices for examples and benchmarks.

**Comment by ashawley** [comment]
While working on GitHub Actions I documented the existing build matrix for Travis:

|Scala|Java|Build   |Scala.js|Native|Workers|
|-----|----|--------|--------|------|-------|
|2.11|1.8  |jvm     |-       |-     |4      |
|2.11|1.8  |js      |1.x     |-     |1      |
|2.12|1.8  |jvm     |-       |-     |4      |
|2.12|1.8  |js      |1.x     |-     |1      |
|2.12|1.8  |js      |0.6     |-     |1      |
|2.13|1.8  |jvm     |-       |-     |4      |
|2.13|1.8  |js      |1.x     |-     |1      |
|2.13|1.8  |js      |0.6     |-     |1      |
|2.12|11   |jvm     |-       |-     |4      |
|2.13|11   |jvm     |-       |-     |4      |
|0.27|1.8  |jvm     |-       |-     |1      |
|2.11|1.8  |native  |-       |0.3   |1      |
|2.11|1.8  |native  |-       |0.4   |1      |
|2.11|1.8  |examples|-       |-     |-      |
|2.11|1.8  |bench   |-       |-     |-      |

**Comment by ashawley** [comment]
Travis had 15 builds jobs, and the current build matrix is 32 jobs.

**Comment by ashawley** [comment]
To be honest, the old build matrix on Travis was trimmed down for efficiency but also because there were certain builds that were unnecessary. Some might have been failing.  That may no longer be the case, though.

**Comment by djspiewak** [comment]
We can almost certainly drop the SJS 0.6 stuff btw

**Comment by larsrh** [comment]
Yeah, let's do that. I may have released broken artifacts anyway (typelevel/squants#425).
