### ISSUE TITLE
Support for 3.0.0-M3 released under 1.5.1

### ISSUE THREAD

**Issue by tgodzik** [typelevel/scalacheck#732]
It seems that there was a typo while releasing and instead of 1.15.1, scalacheck support 3.0.0-M3 got released for 1.5.1.

We could try to go around it, but it would be awesome also if anyone could rerelease it for 1.15.1,

**Comment by larsrh** [comment]
Yeah, that release was botched unfortunately :frowning: We're aware and trying to figure out what to do ASAP.

**Comment by tgodzik** [comment]
we can go around in munit via small hack: https://github.com/scalameta/munit/pull/279/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R256

**Comment by larsrh** [comment]
No, absolutely please don't do that, that will create so much pain downstream!

**Comment by larsrh** [comment]
Since clearly this is a pressing issue I will release a 1.15.2 right away

**Comment by tgodzik** [comment]
> No, absolutely please don't do that, that will create so much pain downstream!

 Sure! I had no idea it might be problematic :fearful: 



> Since clearly this is a pressing issue I will release a 1.15.2 right away

Thanks! It's mostly pressing since I believe some of the typelevel libraries also depend on munit.

**Comment by larsrh** [comment]
1.15.2 is promoting to Maven Central right now

**Comment by larsrh** [comment]
CHANGELOG still pending, but working on it later today

**Comment by tgodzik** [comment]
Thanks a lot!
