### ISSUE TITLE
n-argument `forAll` shrinks less well than n-tuple shrinking

### ISSUE THREAD

**Issue by jonaskoelker** [typelevel/scalacheck#736]
See https://gist.github.com/jonaskoelker/4390fcc8bec868cd3b4f4ef43f29b830, in particular you might want to run the sbt command `testOnly DefaultShrinking`. You will see that shrinking a triple gives you three consecutive integers with 0 being one of them, whereas shrinking three `forAll` arguments gives you a single zero and the two original inputs. I consider the triple shrinking better, and assume pretty much everyone agrees. (Not necessarily better for its cost, merely better.)

I think this a consequence of the n-argument `forAll` being implemented in terms of sequencing a single `forAll` and an (n-1)-argument `forAll`. The obvious solution is for multi-argument `forAll` implementations to call the single-argument `forAll` with a tuple as the argument. It seems _so_ obvious that the fact that it hasn't been implemented yet makes me think I'm missing something ;-)

**Comment by ashawley** [comment]
Yes, this is a known issue.  See #432.  I worked on the very change you suggested, but it didn't turn out to be an easy fix.   It would probably need to be part of a 2.0 release.
