### ISSUE TITLE
Drop the dotty plugin?

### ISSUE THREAD

**Issue by ashawley** [typelevel/scalacheck#784]
Upgrading to sbt 1.5 in #780 gives a warning about sbt-dotty plugin being deprecated:

    The sbt-dotty plugin is no longer neeeded with sbt >= 1.5, please remove it from your build.

**Comment by larsrh** [comment]
This probably requires some extra work since `isDotty` is gone; so either we clean up our build to get rid of version-specific behaviour or we bite the bullet and define it ourselves.

**Comment by SethTisue** [comment]
define-it-ourselves example: https://github.com/circe/circe/pull/1716/files

**Comment by ashawley** [comment]
We have plenty of version-specific bits in the build to go on.

The cicle PR shows how to the replace the `withDottyCompat` syntax that we use for the Scala.js test artifact.  Thanks, Seth.  I guess we can drop after all.
