### ISSUE TITLE
Behavior of Gen.listOfN behaves different to what I was assuming based on the documentation

### ISSUE THREAD

**Issue by L7R7** [typelevel/scalacheck#844]
I have a Generator for a  list of elements. To limit the number of elements in that list, I used `Gen.listOfN` instead of `Gen.listOf`.

[The Scaladoc](https://github.com/typelevel/scalacheck/blob/main/src/main/scala/org/scalacheck/Gen.scala#L1050) says _"Generates a list with at most the given number of elements"_, so I was assuming that the generated lists will have different lengths, but never more than the provided value for the argument `n`. 
But instead what I see is that the lists always seem to be of length `n`.

I would assume that this is the intended behavior and not a bug (based on a quick look at `buildableOfN`, it seems to be intended to aim for `n` elements in the result), so probably I was fooled by the docs.

Theoretically I could go with `Gen.list(...).map(_.take(n))`, but that wouldn't be efficient because the first generator would generate a lot of values that are discarded by `take`.

Or something like:

```scala
def listGen[T](n: Int)(implicit gen: Gen[T]): Gen[List[T]] = {
  for {
    length <- Gen.choose(0, n)
    ts <- Gen.listOfN(length, gen)
  } yield ts
}
```
which feels primitive enough to make me expect it in scalacheck directly.

Am I missing something here? Is there a different way to write an efficient generator for a list that produces lists of different lengths with a given maximum length?

**Comment by rossabaker** [comment]
It does what I expect from the name and not what I expect from the docs and I usually end up sampling to remember what it really does.

I don't know that it should be a primitive, but I've had luck mixing it with Poisson when there's no hard max.  It gives me outliers without killing test performance:

```
val g = Gen.poisson(10).flatMap(n => Gen.listOfN(n, Gen.asciiChar))
```

**Comment by ashawley** [comment]
One concern with fixing is that people have written generators and tests that also do what they "expected", and what ScalaCheck does(!), and not what the doc describes.  However, we could probably try making this change in a major release and add release notes and see how it goes.

**Comment by ashawley** [comment]
I opened an initial PR, #845, to give more variation to the size for `Gen.listOfN`.  This variation only modifies this method for Lists, and won't affect other collections, for the reasons I said above.  There's a chance we could try it for others.

There were tests even in ScalaCheck's test suite that were disrupted by this test. Changing a popular method like `listOfN` is likely going to cause failures for any users who also have fragile tests that are expecting to generate lists of an exact size of _N_.

**Comment by ashawley** [comment]
Georgi Krastev mades a similar conclusion on the PR on what it is that could be done:

> I will just weigh in my opinion as a user - I think changing the behaviour in this way has the potential to break too many tests. Also the current behaviour is consistent with the name `listOfN`. For these reasons I think it would be better to just change the documentation of `listOfN` and add new methods with "at most" semantics. If it's possible, calling `buildableOfN` for `Set` and `Map` could then be deprecated.

**Comment by satorg** [comment]
@L7R7 do you think this issue is safe to be closed now?

**Comment by L7R7** [comment]
Yes, can be closed.
