### ISSUE TITLE
Update website with last 2 years of news

### ISSUE THREAD

**Issue by SethTisue** [typelevel/scalacheck#853]
For a long time we didn't have a way to update https://scalacheck.org with news, so the most recent news item there is from fall 2019.

Volunteer to add in the releases since then...? Including mentioning the changeover to the typelevel org?

https://github.com/typelevel/scalacheck/blob/main/CHANGELOG.markdown is the main relevant resource.

(The website sources are in the `website` branch)

It would also be nice to address:

* update the current version number wherever it appears, for example on https://scalacheck.org/download.html
* update the copyright date everywhere (2019->2021)
* change http links to https where appropriate
* ~fix #574~

and I'm not sure what else.

But any PR that addresses _any_ of this is welcome, no one PR need address _all_ of it.

**Comment by ashawley** [comment]
If you see the commits in #852, Ross made the fix for #574.

We just need Rickard to update the DNS for scalacheck.org to point to the gh-pages.

**Comment by ashawley** [comment]
I can try to make some of these updates.  I'm having trouble getting nix to work on my machine, but was able to get a microsite version of the site sources working with hakyll and cabal.  Although, even that has issues, as well.  Fortunately, I am confident I can edit markdown correctly.

**Comment by ashawley** [comment]
Ok, I've pushed 1ec0847, which has fixes for the glaring issues Seth has pointed out.

If Ross has a chance to publish these, we should be sufficiently updated.

**Comment by SethTisue** [comment]
The change hasn't gone live.

Is there a confusion here between the `website` and `gh-pages` branches...?

**Comment by ashawley** [comment]
The sources are in `website` and the pages are published to `gh-pages` using `./push-site.sh`.  I can't get the build working locally with nix, and we don't have automation, yet.

We just need @rossabaker to republish when he gets a chance.

**Comment by SethTisue** [comment]
Okay. At this point I'm basically just curious, but what's the purpose of having both branches? Is this a standard setup and I'm just not familiar with it?

**Comment by ashawley** [comment]
Nix and Hakyll is non-standard.  That's likely the explanation you're looking for.  Jekyll-based sites can live in gh-pages [by default](https://help.github.com/articles/using-jekyll-with-pages/).

**Comment by SethTisue** [comment]
ahhhhh, duh, okay, of course.

**Comment by rossabaker** [comment]
Sorry, it escaped me that I was the blocker on this.  Anyone should be able to build this with a nix installation and GitHub rights, but the union of those sets may be Rickard and me.

1ec0847 is published.

**Comment by SethTisue** [comment]
it seems something went wrong here — https://scalacheck.org is 404

**Comment by rossabaker** [comment]
That 404 was fixed in #855.

**Comment by SethTisue** [comment]
Nice! So we can close this ticket?

**Comment by rossabaker** [comment]
Yes, I think so.
