### ISSUE TITLE
Website broken (404 from Github)

### ISSUE THREAD

**Issue by borice** [typelevel/scalacheck#854]
Seems like something is wrong with https://www.scalacheck.org as it returns a 404 error from Github pages.  The exact error message is:

```
There isn't a GitHub Pages site here.
```

**Comment by rossabaker** [comment]
I probably broke this last night when I refreshed it.  It looks like the CNAME file is missing.

**Comment by rossabaker** [comment]
Well, I fixed scalacheck.org with #855, but not www.scalacheck.org. :confounded:

**Comment by rossabaker** [comment]
And now https://www.scalacheck.org is working, too.  I didn't do anything to fix it.  Maybe a Cloudflare cache, or maybe an assist from behind the scenes.
