### ISSUE TITLE
Release v1.16.0

### ISSUE THREAD

**Issue by armanbilge** [typelevel/scalacheck#886]
To unblock https://github.com/scalameta/munit/pull/477 and Discipline Native/3 which should get us to Cats Native/3.

**Comment by rossabaker** [comment]
I will cut this tomorrow if nobody tells me to wait.

**Comment by rossabaker** [comment]
Sorry, another bikeshed: is the plugin prepared for tags that don't begin with `v`?  Alternatively, is there any reason we shouldn't switch to the common Typelevel convention now?

**Comment by armanbilge** [comment]
Ah, good question. All tags from this point should start with `v`. MiMa needed some manual intervention to recognize the old artifacts but that's for the better because PVP and stuff.
https://github.com/typelevel/scalacheck/blob/0ac8005753ab98b6494fd631502201b97a103638/build.sbt#L56-L57

**Comment by rossabaker** [comment]
Tagged, but I won't be awake to see the outcome.

**Comment by rossabaker** [comment]
Oh, we should also update the CHANGELOG.  I'll try to remember to do that if it hasn't appeared overnight.
