### ISSUE TITLE
Improvement: Add `nonEmptySomeOf` to complement `someOf`

### ISSUE THREAD

**Issue by vivekragunathan** [typelevel/scalacheck#948]
`someOf` returns 0 or more elements. Would be handy to have a `nonEmptySomeOf` similar how there are other complementary non empty versions.

ref: https://github.com/typelevel/scalacheck/pull/944#issuecomment-1480252026

**Comment by ashawley** [comment]
I believe `atLeastOne` already provides `nonEmptySomeOf`.

**Comment by vivekragunathan** [comment]
Darn .. I did not know such a method already exists. Naming is always tripping. Closing this issue/PR.

**Comment by ashawley** [comment]
Yes the naming is confusing because it's not always consistent. Sometimes the generator's name describes what is done with the arguments and other times it's based on the values returned by the generator.
